### ISSUE TITLE
Inconsistency in the function ForcedIntegersForPseudoFrobenius 

### ISSUE THREAD

**Issue by ojedamc** [gap-packages/numericalsgps#12]
The output of ForcedIntegersForPseudoFrobenius([1,6,7]) is [[1,2,3,6,7],[0,4,5,8]]. This is not possible because 1+5 = 6 should be a non-gap and it is a forced gap.

**Comment by ManuelAFDelgado** [comment]
Fixed.
Thanks a lot for pointing out the problem.

**Comment by ojedamc** [comment]
You are very welcome. Best regards, Ignacio

Departamento de Matematicas
Facultad de Ciencias
Universidad de Extremadura
Avenida de Elvas, s/n
06071-Badajoz (SPAIN)
Phone: +34 924 289300 ext. 86824
