### ISSUE TITLE
Bad implication to IsAttributeStoringRep

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/numericalsgps#25]
The following line is problematic (see https://github.com/gap-system/gap/issues/2818 and https://github.com/gap-system/gap/pull/3006)
```gap
InstallTrueMethod(IsUniquelyPresentedAffineSemigroup, IsGenericAffineSemigroup);
```
This is problematic because `IsUniquelyPresentedAffineSemigroup` is a synonym for `IsAffineSemigroup`, and that in turn is defined as
```gap
DeclareRepresentation( "IsAffineSemigroupRep", IsAttributeStoringRep, [] );
...
DeclareCategory( "IsAffineSemigroup", IsAdditiveMagma and IsAffineSemigroupRep) ;
```
This declaration is the core of the issue: it states that every `IsAffineSemigroup` is automatically given by an `IsAffineSemigroupRep` representation. That already seems strange (normally, you'd want the implication differently: everything in `IsAffineSemigroupRep` also is an `IsAffineSemigroup`, but somebody might want to implement an `IsAffineSemigroup` object in a different representation.

But in any case, it means that we now have this implication chain:
```
IsGenericAffineSemigroup => IsUniquelyPresentedAffineSemigroup => IsAffineSemigroup => IsAffineSemigroupRep => IsAttributeStoringRep
```

Future GAP versions will reject implications that imply specific representations, as they usually are an error.

It would be great if you could change this. The easiest potential fix would essentially swap the category and representation:
```gap
DeclareCategory( "IsAffineSemigroup", IsAdditiveMagma );
DeclareRepresentation( "IsAffineSemigroupRep", IsAttributeStoringRep and IsAffineSemigroup, [] );
```

**Comment by pedritomelenas** [comment]
Thank you @fingolfin 
The problem is I assume autocompletion ... 
`DeclareSynonymAttr("IsUniquelyPresentedAffineSemigroup", IsAffineSemigroup);`
must be 
`DeclareSynonymAttr("IsUniquelyPresentedAffineSemigroup", IsUniquelyPresented);`

I hope that with this is fine. I will correct it later.

Thank you so much,
Pedro
