### ISSUE TITLE
Make a new release from github, using ReleaseTools

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/numericalsgps#3]
Please make a new release, using [ReleaseTools](https://github.com/fingolfin/ReleaseTools), by following all the instructions given there.

**Comment by fingolfin** [comment]
Once that happened, you can tell @alex-konovalov to change the GAP distribution to point to this repository. (Until then, this should *not* be done, because I hacked the `PackageInfo.g` on GitHub pages to point to the old 1.0.1 release for now)

**Comment by pedritomelenas** [comment]
Thanks @fingolfin for the help migrating the repo here. We will close the issue when we do an update with ReleaseTools.

**Comment by pedritomelenas** [comment]
Done by Manual
