### ISSUE TITLE
Issues in the function ArfGoodSemigroupClosure

### ISSUE THREAD

**Issue by nicolamaugeri** [gap-packages/numericalsgps#40]
The function ArfGoodSemigroupClosure does not seem to work. For example, if you try to compute the Arf Closure of the good semigroup S, with Small(S)={(0,0),(2,4),(3,7),(4,8),(5,9)}, it returns S itself that is not Arf.
The problem in the algorithm seems to be that this one does not consider the compatibility level in the multiplicity tree (see. Proposition 1.2 in Giuseppe Zito - Arf good semigroups). So it returns a semigroup that can be strictly contained in the Arf closure.

**Comment by pedritomelenas** [comment]
@nicolamaugeri thank you! I let you fix it.

**Comment by pedritomelenas** [comment]
Fixed by @nicolamaugeri in #41 
Thanks @nicolamaugeri and @GiuseppeZito !
