### ISSUE TITLE
Make a release?

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/numericalsgps#42]
Hi there, could I perhaps convince you to make a release before mid-april / may? We are waiting for  https://github.com/gap-packages/numericalsgps/issues/25 to appear in a released version of numericalsgps.

**Comment by pedritomelenas** [comment]
Sure. Manuel will be back on Tuesday. And #25 was a really bad typo... 
The package has several new functionalities, and thus some potential bugs also... 
Thank youj,
Pedro

**Comment by pedritomelenas** [comment]
Done by @ManuelAFDelgado
