### ISSUE TITLE
Tests fail in GAP master branch

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/numericalsgps#57]
See e.g. here: https://travis-ci.org/gap-infra/gap-docker-pkg-tests-master/jobs/659449717

```
########> Diff in /home/gap/inst/gap-master/pkg/NumericalSgps-1.2.1/tst/testal\
l.tst:1054
# Input is:
SmallElements(s);
# Expected output:
[ 0, 4, 8, 12, 16, 20 ]
# But found:
[ 0, 4 .. 20 ]
########
########> Diff in /home/gap/inst/gap-master/pkg/NumericalSgps-1.2.1/tst/testal\
l.tst:1328
# Input is:
SmallElements(I);
# Expected output:
[ 3, 5, 7, 9, 11, 13 ]
# But found:
[ 3, 5 .. 13 ]
########
```

This does not happen in stable-4.11 branch. Perhaps you can check the way you check the output of `SmallElements` to make it pass in both master and stable-4.11 branches.

**Comment by pedritomelenas** [comment]
Goto #56

**Comment by alex-konovalov** [comment]
Ah right! I transferred it to "staging" tests today, and was not sure if I reported it.
