### ISSUE TITLE
Wrong output in "DivisorsOfElementInNumericalSemigroup"

### ISSUE THREAD

**Issue by Ataraxta** [gap-packages/numericalsgps#63]
For the semigroup of the natural numbers, the function fails for the element 1:

gap> N:=NumericalSemigroup(1);
<The numerical semigroup N>
 gap> DivisorsOfElementInNumericalSemigroup(1,N);
 [  ]
 gap> DivisorsOfElementInNumericalSemigroup(0,N);
 [ 0 ]

DivisorsOfElementInNumericalSemigroup(1,N); should output [0,1]

**Comment by pedritomelenas** [comment]
Thanks! solved in https://github.com/gap-packages/numericalsgps/commit/a82ecaf6a9513fdf684e5fdf36dd8111619d00d3
