### ISSUE TITLE
Incorrect delegation between printing functions

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/numericalsgps#74]
The GAP library has a bewildering number of functions for printing/viewing/displaying objects to the terminal or into a string. There is a strict hierarchy how methods for the various involved operations may delegate, [described in the GAP reference manual](https://docs.gap-system.org/doc/ref/chap6.html#X8074A8387C9DB9A8).

The following methods in `numericalsgps` violate this:

- in `gap/numsgp-def.gi:575`: `InstallMethod(String,[IsNumericalSemigroup],ViewString);`
- in `gap/affine-def.gi:1315`: `InstallMethod(String,[IsAffineSemigroup],ViewString);`

To fix this, just install the two `ViewString` methods for `String` instead and then delegate "the other way around".

**Comment by pedritomelenas** [comment]
solved in https://github.com/gap-packages/numericalsgps/commit/c5404894635a37c5eabaeca087fb5212e83a44da

**Comment by fingolfin** [comment]
Thank you!
